name: GitHub Classroom Workflow
on: [push]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding@v1
